[tools]
bitwarden = "latest"
chezmoi = "latest"
direnv = "latest"
gcloud = "latest"
go = "latest"
helm = "latest"
kubectx = "latest"
kubens = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
ruff = "latest"
rust = "latest"
uv = "latest"
vale = "latest"
zellij = "latest"
zoxide = "latest"
